name: 'action-element-snapshot'
description: 'Take an element screenshot'
inputs:
  source_url:
    description: 'Location of the element'
    required: true
  token:
    description: 'Github token'
    required: true
outputs:
  image_url:
    description: 'Location of the screenshot'
    runs:
      using: 'docker'
      image: 'Dockerfile'
      env:
        INPUT_SOURCE_URL: ${{ inputs.source_url }}
        INPUT_TOKEN: ${{ inputs.token }}
